/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin

class Client {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Client().greeting)
}
